In [ ]:
x = sub("Hello", 0, 1)

NameError: ignored

In [ ]:
x = "Hello"[-1]
x

'o'

In [ ]:
x = "Hello".sub(0,1)

AttributeError: ignored

In [5]:
# Sum of a list using for loop

a = [1,2,3,4,5]
sum = 0
for i in a:
  sum += i
print(sum)

15


In [ ]:
# Sum of a list using while loop

a = [5,4,2,8,1,25]
sum = 0
i = 0
while i < len(a):
  sum += a[i]
  i += 1
print(sum)  

45


In [ ]:
# Reverse a list

a = [1,2,3,4,5]
rev = []
for i in a:
  rev = [i] + rev
print(rev)

[5, 4, 3, 2, 1]


In [ ]:
# Reverse a given string

num = 'sagar'
rev = ''
for i in num:
  rev = i + rev
print(rev)

ragas


In [28]:
# Reverse a given mumber

num = 9819292
digit = 0
rev = 0
while num > 0:
  digit = num % 10
  num //= 10
  rev = digit + rev*10
print(rev)

2929189


In [22]:
a = 12345
rev = 0
while a > 0:
  rev = a%10
  a//= 10
  print(rev, end = '')

54321

In [ ]:
# Count digits in a number

num = 1993
count = 0
while num > 0:
    num //= 10
    count += 1
print(count)

4


In [34]:
# count odd numbers in a given number

num = 16566818
digit = 0
count = 0
while num > 0:
  digit = num % 10
  num //= 10
  if digit % 2 == 1:
    count += 1
print(count)

3


In [ ]:
# Highest digit in a number

num = 1681936598
digit = 0
temp = 0
while num > 0:
  digit = num % 10
  num //= 10
  if digit > temp:
      temp = digit
print(temp)

9


In [ ]:
# sum of numbers using default parameter in function

def sum(a,b,c=2,d=5):
  return a+b+c+d
a = int(input())
b = int(input())
sum(a,b)

5
2


14

In [ ]:
# Insert element in a list

a = [5,4,2,8,6,1]
a.insert(2,44)
a

[5, 4, 44, 2, 8, 6, 1]

In [ ]:
# Sum of num till hit -1

sum = 0
while num != -1:
  num = int(input())
  sum = sum + num
print(sum+1)

2
4
4
-1
10


In [ ]:
# Find greatest of the numbers in a list

import functools
num = [4,8,5,7,9,2,4]
greatest = functools.reduce(lambda a,b : a if a>b else b, num)
print(greatest)

9


In [66]:
# Filter even numbers in a list

a = [5,2,3,8,3,4,6]
print(list(filter(lambda x: x%2 == 0, a)))

TypeError: ignored

In [64]:
l = [1,5,7,4,5,6,2]
a = list(filter(lambda x: x%2 == 0, l))

TypeError: ignored

In [ ]:
# Find factorial of a number

num = int(input())
fact = 1
while num > 0:
  fact *= num
  num -= 1
print(fact)

5
120


In [ ]:
# Count letters in a string

a = 'elephant'
b = {}
for i in a:
  if i in b:
    b[i] += 1
  else:
    b[i] = 1
print(b)

{'e': 2, 'l': 1, 'p': 1, 'h': 1, 'a': 1, 'n': 1, 't': 1}


In [ ]:
# Print number with its square from 1 to 10

a = {}
for i in range(1,11):
  a[i] = i**2
print(a)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


In [ ]:
# Print square of numbers in a list

a = [1,2,3,4,5]
for i in range(len(a)):
  a[i] = a[i]**2
print(a)

[1, 4, 9, 16, 25]


In [ ]:
# Combine 2 sets into list

a = {"as", "df", "asd"}
b = {"12", "54", "frg"}
list(zip(a,b))

[('df', 'frg'), ('asd', '54'), ('as', '12')]

In [ ]:
# Combine 2 lists into dictionary

a = ["as", "df", "asd"]
b = ["12", "54", "frg", "ss"]
d = {}
for i,j in zip(a,b):
  d[i] = j
d

{'as': '12', 'df': '54', 'asd': 'frg'}

In [ ]:
# Define a function to find number is even or odd

def num(a):
  if a % 2 == 0:
    return "Even"
  else:
    return "Odd"
num(13)

'Odd'

In [ ]:
# Rotate a set of numbers separated by space by times specified.

a = input("Enter numbers separated by space: ")
b = int(input("Enter no.of rotations: "))
a = a.split()
for i in range(b):
  a.insert(0, a.pop())
for i in a:
  print(i, end = " ")

Enter numbers separated by space: 1 2 3 4 5
Enter no.of rtations: 3
3 4 5 1 2 

In [ ]:
# Find mean of a given list of numbers

a = [1,3,5,6,8,7]
sum = 0
for i in a:
  sum += i
print("Mean = ", sum/len(a))

Mean =  5.0


In [ ]:
# List out 10 random numbers btwn 10 and 100

import random
a = [random.randint(10,100) for i in range(10)]
a

[93, 88, 41, 72, 37, 89, 25, 53, 92, 74]

In [ ]:
# Sum of values in a dictionary

a = {'apple':25, 'mango':20,'orange':100}
sum = 0
for i in a.values():
  sum += i
print(sum)

145


In [ ]:
# Print only string before @
a = 'sftvhhsfggsg@@@$$$_#__'
print(a.split('@')[0])

sftvhhsfggsg


In [ ]:
# Regular expression

import re

In [ ]:
DS17 = "DS17, is in the fourth week of Python"
print(re.findall("[Z]", DS17))
print(re.findall("[^A-Z]", DS17))

[]
['1', '7', ',', ' ', 'i', 's', ' ', 'i', 'n', ' ', 't', 'h', 'e', ' ', 'f', 'o', 'u', 'r', 't', 'h', ' ', 'w', 'e', 'e', 'k', ' ', 'o', 'f', ' ', 'y', 't', 'h', 'o', 'n']


In [ ]:
#  Factorial of a number using recursion

def rec(n):
  if n == 1:
    return 1
  else:
    return n * rec(n-1)
rec(5)

120

In [ ]:
# Create 1D array using 0s and 1s

import numpy as np
a = np.ones(5)
b = np.zeros(4)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0.]


In [ ]:
# Create a matrix of 5 x 3 

np.random.randint(10,70,15).reshape(5,3)

array([[47, 34, 44],
       [63, 38, 46],
       [32, 65, 21],
       [66, 18, 61],
       [42, 35, 26]])

In [ ]:
# Use lambda to add 100 to ant numberpassed as an argument

a = lambda x : x+100
a(100)

200

In [ ]:
# Lambda function to return min of 2 elements

import functools
l = [10,20,35,100,25,31,200]
ret = functools.reduce(lambda x,y : x if x<y else y, l)
ret

10

In [ ]:
# WAP to multiply all elements in a tuple using lambda

my_tuple = (9,5,3)
import functools
ret = functools.reduce(lambda x,y : x*y, my_tuple)
ret

135

In [ ]:
# WAP to triple all numbers in a list
l = [2,5,8,9,6]
a = []
for i in l:
  a.append(i*3)
print(a)

[6, 15, 24, 27, 18]


In [ ]:
# OR

print(list(map(lambda x : x+x+x, l)))

[6, 15, 24, 27, 18]


In [ ]:
# WAP to remove all occurances of 10 from a list of numbers
a = [10,20,5,10,3,4,6]
print(list(filter(lambda x : x!=10, a)))

[20, 5, 3, 4, 6]


In [ ]:
# WAP to convert list of words to upercase using lambda

a = ["apple", "mango", "orange"]
print(list(map(lambda x : x.upper(), a)))

['APPLE', 'MANGO', 'ORANGE']


In [ ]:
# WAP to find LCM of 2 numbers recursively

def hcf(a,b):
  if b == 0:
    return a
  else:
    return hcf(b, a%b)

def lcm(a,b):
  return (a*b)//hcf(a,b)

first = int(input())
second = int(input())

print("LCM of", first, "and", second, "is", lcm(first, second))

2
3
LCM of 2 and 3 is 6


In [ ]:
# WAP to listify the list of given strings individually using map

colour = ["Red","Blue","Black","White","Pink"]
print(list(map(list, colour)))

[['R', 'e', 'd'], ['B', 'l', 'u', 'e'], ['B', 'l', 'a', 'c', 'k'], ['W', 'h', 'i', 't', 'e'], ['P', 'i', 'n', 'k']]


In [ ]:
# WAP to create a 8x8 matrix in checkerboard pattern

import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern: ")
x = np.zeros((8,8),dtype = int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

Checkerboard pattern: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Create a 2D array with 1 on the border and 0 inside

import numpy as np
x = np.ones((5,5))
print(x)
x[1:-1,1:-1]=0
print("\n",x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Create a 3x3 matrix with values ranging fro 0 to 8

x = np.arange(0,9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Create a vector with values ranging from 10 to 49 and then reverse the vector

v = np.arange(10,49)
print(v)
print(np.flip(v))
# print(v[::-1])
# axis = 0 reverse rows
# axis = 1 reverse columns

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# Find indices of non-zero elements

a = [1,2,0,0,4,0]
nonzeroind = np.nonzero(a)[0]
print(nonzeroind)

[0 1 4]


In [ ]:
# WAP that generates fibonacci sequence of n numbers using recursion

def fib(n):
  if n <=1:
    return n
  else:
    return fib(n-1)+fib(n-2)
n = int(input())
print("Fibonacci sequence: ")
for i in range(n):
  print(fib(i), end = ' ')

5
Fibonacci sequence: 
0 1 1 2 3 

In [ ]:
# Check whether a number is even or odd using lambda

a = int(input())
res = lambda x: "Even" if x%2 == 0 else "Odd"
print(res(a))

5
Odd
